App\Entity\Customer:
  properties:
    email:
      - NotBlank: ~
      - NotNull: ~
      - Email:
          message: The email "{{ value }}" is not a valid email.
    phone:
      - NotBlank: ~
      - NotNull: ~
      - Regex:
          pattern: '/(?:\+7\()[0-9]{3}[\)][0-9]{3}[\-][0-9]{2}[\-][0-9]{2}/'
          message: Wrong phone pattern. Use +7(###)###-##-##